apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpc-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpc-operator
rules:
  - apiGroups: ["hpc.dolevalg.com"]
    resources: ["hpcjobs", "hpcclusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpc-operator
roleRef:
  kind: ClusterRole
  name: hpc-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: hpc-operator
    namespace: default