apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hpcjobs.hpc.dolevalg.com
spec:
  group: hpc.dolevalg.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Namespaced
  names:
    plural: hpcjobs
    singular: hpcjob
    kind: HPCJob
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hpcclusters.hpc.dolevalg.com
spec:
  group: hpc.dolevalg.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Namespaced
  names:
    plural: hpcclusters
    singular: hpccluster
    kind: HPCCluster