apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-operator
  labels:
    app: hpc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-operator
  template:
    metadata:
      labels:
        app: hpc-operator
    spec:
      serviceAccountName: hpc-operator
      containers:
        - name: hpc-operator
          image: <operator-image>
          args:
            - "--metrics-addr=0.0.0.0:9090"
            - "--rest-server-addr=0.0.0.0:8080"
          ports:
            - containerPort: 8080
            - containerPort: 9090